theme = "tokyonight_storm"

[editor]
# scrolloff = 999
line-number = "relative"
mouse = false
bufferline = "multiple"
auto-format = true
auto-completion = true
color-modes = true
end-of-line-diagnostics = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection" ]
C-r = [ ":redraw" ]

# Selecting
C-n = [ "move_char_left", "move_next_word_end", "move_prev_word_start", "search_selection"]
C-m = [ "match_brackets", "select_mode", "match_brackets", "normal_mode", "search_selection" ]
C-b = [ "move_char_left", "move_next_long_word_end", "move_prev_long_word_start", "search_selection"]

C-z = ["move_char_left", "move_next_word_end", "move_prev_word_start", "search_selection", "select_all", "select_regex"]
C-Z = ["search_selection", "select_all", "select_regex"]

# Moving
A-h = [ "delete_selection", "move_prev_long_word_start" , "paste_before" ]
A-j = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
A-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-l = [ "delete_selection", "move_next_long_word_end", "paste_after" ]

# Git
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

# Navigating
C-H = [ "goto_previous_buffer"]
C-L = [ "goto_next_buffer"]

C-h = [ "jump_view_left"]
C-j = [ "jump_view_down"]
C-k = [ "jump_view_up"]
C-l = [ "jump_view_right"]

C-left = [ "swap_view_left"]
C-down = [ "swap_view_left"]
C-up = [ "swap_view_up"]
C-right = [ "swap_view_right"]

# Window/buffer
C-Q = [ ":bc" ]
C-S = [ ":w" ]

A-v = [ "vsplit" ]
A-s = [ "hsplit" ]
A-q = [ ":q" ]
A-Q = [ ":q!" ]

C-a = [ ":format" ]

[keys.select]
"C-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"C-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true
